# Configure the matching service adapter's server settings here.
# See http://www.dropwizard.io/1.0.5/docs/manual/configuration.html#servers
# for more information.
server:
  # Ports on which to listen for normal connections.
  # See http://www.dropwizard.io/1.0.5/docs/manual/configuration.html#connectors
  # for information on HTTPS and TLS connections.
  applicationConnectors:
    - type: http
      port: ${PORT:-8080}
  # Ports on which to listen for admin tasks.
  # This can probably be set to the above port+1.
  adminConnectors:
    - type: http
      port: ${ADMIN_PORT:-8081}

# Add information about your matching service adapter (MSA) here.
matchingServiceAdapter:
  # The entityId is used for SAML communication with Verify.
  entityId: ${MATCHING_SERVICE_ENTITY_ID:-}
  # The externalUrl is the internet-facing URL for your MSA.
  externalUrl: ${MATCHING_SERVICE_POST_URL:-}

# Configure the URLs for your local matching service here.
localMatchingService:
  # The matchUrl is where the MSA should post user attributes on a successful match
  matchUrl: ${LOCAL_MATCHING_SERVICE_MATCH_URL:-}
  # The accountCreationUrl is where the MSA should post attributes for unknown users
  accountCreationUrl: ${ACCOUNT_CREATION_URL:-}

# Configure the key pairs used by your MSA for signing SAML messages here.
signingKeys:
  # The primary signing key is used to sign all messages to Verify.
  primary:
    publicKey:
      # The certificate (.crt) containing the primary public signing key:
      certFile: ${PRIMARY_PUBLIC_SIGNING_KEY_CRT_PATH:-}
      # The common name (CN) of that certificate:
      name: ${PRIMARY_PUBLIC_SIGNING_KEY_CRT_COMMON_NAME:-MSA Signing}
    privateKey:
      # The PK8 (.pk8) containing the primary private signing key:
      keyFile: ${PRIMARY_PRIVATE_SIGNING_KEY_PK8_PATH:-}
  # The public part of the secondary signing key is published in the MSA's metadata
  # during key rollovers but is otherwise unused by the MSA.
  secondary:
    publicKey:
      certFile: ${SECONDARY_PUBLIC_SIGNING_KEY_CRT_PATH:-}
      name: ${SECONDARY_PUBLIC_SIGNING_KEY_CRT_COMMON_NAME:-Secondary MSA Signing}
    privateKey:
      keyFile: ${SECONDARY_PRIVATE_SIGNING_KEY_PK8_PATH:-}

# Configure the key pairs used by your MSA for encrypting and decrypting SAML
# messages here. You can configure up to 2 encryption keys at a time and the MSA
# will attempt decryption with both. Only the first key will be used for encryption.
encryptionKeys:
  - publicKey:
      certFile: ${PRIMARY_PUBLIC_ENCRYPTION_KEY_CRT_PATH:-}
      name: ${PRIMARY_PUBLIC_ENCRYPTION_KEY_CRT_COMMON_NAME:-MSA Encryption}
    privateKey:
      keyFile: ${PRIMARY_PRIVATE_ENCRYPTION_KEY_PK8_PATH:-}
  - publicKey:
      certFile: ${SECONDARY_PUBLIC_ENCRYPTION_KEY_CRT_PATH:-}
      name: ${SECONDARY_PUBLIC_ENCRYPTION_KEY_CRT_COMMON_NAME:-Secondary MSA Encryption}
    privateKey:
      keyFile: ${SECONDARY_PRIVATE_ENCRYPTION_KEY_PK8_PATH:-}

# Settings for connecting with the hub can be configured here
# if necessary.
hub:
  ssoUrl: ${VERIFY_HUB_URL:-https://www.signin.service.gov.uk/SAML2/SSO}

# Settings for obtaining Verify's metadata can be configured here.
metadata:
  environment: ${METADATA_ENVIRONMENT:-}
  url: ${METADATA_URL:-https://www.signin.service.gov.uk/SAML2/metadata/federation}
  trustStore:
    path: ${METADATA_TRUST_STORE_PATH:-prod_ida_metadata.ts}
    password: ${METADATA_TRUST_STORE_PASSWORD:-puppet}

# Including this section will enable European identities and the universal dataset for matching
# European identities are NOT enabled for production yet so this should remain false
europeanIdentity:
  enabled: false
  hubConnectorEntityId: https://www.signin.service.gov.uk/SAML2/metadata/connector

  # Details about eIDAS metadata can be configured here
  aggregatedMetadata:
    jerseyClientName: trust-anchor-client
    trustAnchorUri: https://www.signin.service.gov.uk/SAML2/metadata/trust-anchor
    metadataSourceUri: https://www.signin.service.gov.uk/SAML2/metadata/aggregator
    trustStore:
      path: prod_ida_metadata.ts
      password: puppet

## Options to add additional logging. By default, logs will be output to console.
## See http://www.dropwizard.io/1.0.5/docs/manual/configuration.html#logging
## for more information.
#logging:
#  level: INFO
#  appenders:
#    - type: file
#      currentLogFilename: apps-home/test-rp-msa.log
#      archivedLogFilenamePattern: apps-home/test-rp-msa.log.%d.gz
#      logFormat: '%-5p [%d{ISO8601,UTC}] %c: %X{logPrefix}%m%n%xEx'
#    - type: console
#      logFormat: '%-5p [%d{ISO8601,UTC}] %c: %X{logPrefix}%m%n%xEx'
